# Site settings
title: Internet Imagery
email: jason.dixon.email@gmail.com
description: For the love of animation. Projects, information and of course an Animator.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://internetimagery.com"
github_username:  internetimagery
exclude:
  - working

# Syntax highlighting
highlighter: rouge #pygments

# Build settings
markdown: kramdown

# Sass Settings
sass:
    style: :compressed

# Prose settings
prose:
  rooturl: "/news/_posts"
  siteurl: "http://internetimagery.github.io"
  media: "/img/posts"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "thumb"
        field:
          element: "text"
          value: ""
          label: "Thumbnail"
      - name: "title"
        field:
          element: "text"
          value: ""
          label: "Page Title"
